- src/remark/controllers/inputs/keyboard.js
The slideshow containing the docs says pushing "P" will toggle presenter mode. This is in fact only true when you push "p", so without shift. This fix makes sure both "P" and "p" are correct. This will cause less confusion.
> Allow uppercase letters to send toggles.

- Gruntfile.js
- package.json
Adds live reloading using `grunt-contrib-watch`.
To use, enter `grunt serve` (default port: 8000) or specify the port using `grunt serve --port 8765`.
> Add live reloading (via Grunt)

- make.js
- package.json
When using shelljs' exec function, the stdout output of the executed
process is mangled with the stderr output.
This causes deprecation warnings like `util.print: Use console.log
instead` to appear e.g. in out/remark.min.js when using an up-to-date
nodejs binary (v0.12.2) after running `node make minify`.
Using the `-o` output file option solved this problem easily because
it circumventes the broken shelljs output handling.
The same problem arises when running the less compiler.
Trying to upgrade the less compiler to the latest version did remove
the warning, in exchange for a new one:
```
The compress option has been deprecated. We recommend you use a
dedicated css minifier, for instance see less-plugin-clean-css.html
```
This message appeared in the generated `src/remark/resources.js` …
> Silence build tools to prevent garbage output

- index.html
Remove redundant attribute/value pairs, etc. This simplifies the “installation” instructions, too!
> Clean up HTML

- remarkise.html
Fixes gnab/remark#168.
Also, cleans up a few things:
* Remove `console.log()` messages
* Make substitution patterns case-insensitive
* Reset page after last error, so that a new URL can be entered by the user, and processed
(Now that I look at it again, my JS code is ugly and convoluted. I shall rewrite [Remarkise](https://gnab.github.io/remark/remarkise) soon&hellip;)
> Avoid trying to fetch the same URL again when a substitution pattern doesn't apply

- src/remark.less
The presenter mode for remark is better than anything I've ever used (even Keynote). I love having the slides stacked on one side and the notes on the other.
However, I found the notes a little difficult to read. This increases the contrast by making the background white, and lightening the elements labels that are fixed. What do you think?
> Increase contrast of presenter notes

- src/remark.less
(re-trying the pull request, something went wrong with the earlier one, apologies about that one).
I quite liked the idea of @bkeepers in https://github.com/gnab/remark/pull/255 to have a black background on body and also liked @gnab's suggestion to only have that on a body:fullscreen - so went ahead to do that as it was easy to do.
> adding CSS to set black background on body:fullscreen

- README.md
It appears that markdowner.com produces server error 503 but www.markdowner.com is fine.
> Fix markdowner link

- remarkise.html
I love remark.js and like that it is possible to just open a markdown file from another server via remarkise. However, at work I am not allowed to upload my presentation files to servers. That is the reason why I added the support for drag and drop.
It uses the FileReader API, and the drop-area is not shown if the browser does not support this feature.
> Added Drag'n'Drop ability in remarkise

- src/remark/views/slideView.js
- test/remark/views/slideView_test.js
I like to have full screen image backgrounds that cover the entire slide.  I also need to be able to switch between 16:9 and 4:3.  Using `background-size: cover` and `background-position: 50% 50%` is a great way to get this.  Instead of more logic, just let the user override this and respect that.
> Allow users to override background-size and background-position

- remarkise.html
[Remarkise](https://gnab.github.io/remark/remarkise): fix gnab/remark#301 by showing better error messages and advising the user when we detect a probable violation of the same-origin policy (or CORS not working).
This tries to detect cross-domain requests by simply comparing origins.
While at it:
* Bugfix: don't change message in `#drop-area` too (that should remain unchanged); feedback messages via subheading only
* Add button to form for better usability; listen to events in both text field and button
* Detect wrong URLs and tell the user, eg `hhtp://typo-in-protocol.com`
* Simplify selectors (CSS and jQuery); optimise selectors: run them just once!
* Use latest version of jQuery
* Add `viewport` meta header (for iPhone)
* Switch to JS' *strict mode*
* Coding style:
* Use `const` …
> Remarkise: better feedback, detect SOP issues

- README.md
Mention DeckTape as an alternative to printing to PDF.
Fixes #313
> Add printing documentation section

- README.md
Markdowner.com domain no longer works and github issue https://github.com/mikaelbr/markdowner/issues/8 confirms project no longer active.
> Remove markdowner from README.md as project no longer exists #354

- README.md
- "Lecture notes using remark", originally http://ozan.keysan.me/ee361/, moved to http://keysan.me/ee361/
- [Markdowner](http://www.markdowner.com/) is dead. I removed the link completely, but alternatively a link to one of the following similar sites could be added [Dillinger](http://dillinger.io/), [StackEdit](https://stackedit.io/editor), [jbt.github.io/markdown-editor/](https://jbt.github.io/markdown-editor/) or [Markable.in](https://markable.in/)
- [Remarks](http://remarks.sinaapp.com/) is also dead and I couldn't find any alternative.
> Update and remove broken links

- src/remark.js
- src/remark/components/printing/printing.js
- src/remark/converter.js
- src/remark/models/slide.js
- src/remark/views/slideView.js
- src/remark/views/slideshowView.js
Re content classes: the following markup would output `[Object object]` instead of the content class' inner markup if used with template inheritance. eg:
layout: true
Header text
{{ content }}
Footer text
---
.left-column[
]
.right-column[
body text
]
Re include path fixes: not sure what build system you were using, but needed to set all include paths to be relative in order to load `remark/src/remark/api` etc directly into node, rollup or webpack.
> Fix content classes with inherited templates, include path fixes

- package.json
This helps automatic parsers determine licenses for legal departments; see https://docs.npmjs.com/files/package.json#license
> Add SPDX-compatible "MIT" license to package.json

- make.js
- package.json
Before: fatal errors in run() print a stacktrace and no output
After: fatal errors in run() are caught and dump stdout
> Upgrade shelljs to 0.7.0 and fix fatal error handling

- src/remark/models/slideshow.js
- src/remark/models/slideshow/navigation.js
In my experience, it's distracting to close an old "clone" and move a new
"clone" into place between presentations of multiple slide shows. This patch
parameterizes the "target" to `window.open` so that the current behavior (e.g.
a new window for each clone) is preserved, but users may opt-in to a "shared
clone" behavior. I'm suggesting that we parameterize the "name" itself (instead
of exposing this as a boolean configuration value) so that users have more
control over how clones are managed.
Thanks for the great tool!
Commit message:
> Presentations built with Remark.js may span multiple HTML files. In such
> contexts, managing the distinct windows created by each "clone"
> operation can be disruptive to the flow of the presentation.
>
> Allow for configuration of the "cloned" window's …
> Implement `cloneTarget` option

- remarkise.html
As it is now, an instance of Remarkise sitting under `https://legit.com` can load and process `https://evil.com/exploit.md` (if that origin enables CORS), and scripts contained there will be executed. That enables XSS attacks.
This PR restricts sources to the same origin.
---
h/t @tobie for bringing this to my attention.
> Restrict markdown sources to same origin to prevent XSS

- README.md
Hey there! My Git-based Markdown wiki engine written in PHP, Repositorium, allows you to view any Markdown page as a remark slideshow with one click. I thought maybe you'd like to feature it in your list of systems integrating with remark. Cheers!
> Add pille1842/repositorium to systems using remark

- README.md
Previous github link redirects twice to a HTTP address.
Further details given in the conversation for #418 .
> Fix #418 'mixed content' error due to redirect

- src/remark/models/slideshow.js
*Long time user, first time contributor... ;-)*
This patch adds an option exclude slides
depending on their class. This allows to turn
on or off chapters, sections, or extra material
very easily. Example:
```
var slideshow = remark.create({
ratio: '16:9',
excludedClasses: ["in-person", "extra-details"]
});
```
With this setting, all slides having `class: in-person`
or `class: extra-details` will be skipped, as if they
had the `excluded: true` property.
My use case is the following: I have a rather big slides
deck (~350 slides) that I use for workshops and tutorials.
I often enable and disable sections, depending on
how long the tutorial should be; what people want to
learn; and whether people are doing this with an
instructor, or at their own pace at home. I used to
enable and disable …
> Allow to exclude sets of slides by class

- README.md
I just finished [Backslide](https://github.com/sinedied/backslide), a complete CLI tool to ease the creation, editing and exporting of Remark presentation 😋 
I added a link reference to it in your readme file, thought that some people might be interested ;)
Thanks for the nice job with Remark BTW! 👍
> Added Backslide reference

- src/remark.less
Enabled scroll when slide contents is longer than page height.
> enable scroll slide content

- src/remark/views/slideView.js
- test/remark/views/slideView_test.js
Now there are three kinds of values one can assign to highlightSpans:
* `false`: span highlighting is off
* `true`: enables backticks for highlighting
* A RegExp: custom delimiters. For example:
```js
highlightSpans: /«([^»]+?)»/g,
```
I’m prefixing the escape capture group to the user-provided regular expression, which is not pretty, but the most concise solution I could find.
> Allow custom delimiters for highlightSpans

- src/remark/views/slideView.js
Used it with real-world slides, encountered a bug in my code, fixed it.
> Fixed a bug in highlightBlockSpans()

- README.md
Hello
Thanks for the great presentation tool!
I created cli tool for serving and building remark slideshow from markdown input file, called `remarker`, and I added the link to it in README.md.
Thanks
---
**Note:**
This tool is similar to `backslide` but doesn't require html, js and css files at all. It directly serves and builds from only input markdown file, so you don't need to manage files except markdown file and that's the point of it.
> docs: add link to remarker

- src/remark/controllers/inputs/keyboard.js
Remark uses several keyboard shortcuts with no accelerator key (eg. `p` for presenter mode). In some off-the-shelf browser configurations this triggers functionality (for instance, to search for matching links). As a general rule, keys handled for actions should not also trigger their default behaviour.
This patch simply calls `preventDefault()` in applicable cases.
> Prevent default on keys that can trigger browser functionality like fast search

- boilerplate-remote.html
- boilerplate-single.html
boilerplate-local had notes for the first slide, the other two
boilerplates did not. Copied the nodes over, so the only differences
between the slides were semantic in nature, not content.
> Normalize boilerplate-{remote,single} with local.

- package.json
`marked` 0.3.1 seems having 2 known vulnerabilities (1 XSS and 1 ReDoS) and both are fixed at v0.3.4. This PR updates `marked` to v0.3.4.
See https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-8854 and https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-1370 for details.
> Update marked for security fix

- src/remark/models/slideshow.js
- src/remark/parser.js
Introduce new option disableIncrementalSlides; if set to true, flatten out incremental slides into single slide with all the contents. Ideally for slide printouts!
> Option for disabling incremental slides

- src/remark/components/slide-number/slide-number.js
- src/remark/controllers/inputs/keyboard.js
- src/remark/models/slide.js
- src/remark/models/slideshow.js
- src/remark/models/slideshow/navigation.js
- test/remark/components/slide-number_test.js
- test/remark/controllers/defaultController_test.js
- test/remark/models/slide_test.js
- test/remark/models/slideshow_test.js
- test/remark/views/slideView_test.js
* Move slide number computation into the Slideshow and constantly store the result in each Slide instance.
* Provide an index for slides by their display number in the Slideshow.
* Provide a new message 'gotoSlideNumber' that navigates to the first slide of a given display number.
* Updated tests for the new Slide constructor.
This will fix #494.
> Make keyboard navigation respect non-countable slides

- .travis.yml
Node.js `0.10` is OLD.
This addresses my comment here: https://github.com/gnab/remark/commit/bb1a48f0da6f754721bab4a133a057b147b0286a#commitcomment-26719952.
This build is failing here due to the bug that #497 fixes; both PRs should be merged. (See here [successful builds with Node.js 6 and 8](https://travis-ci.org/tripu/remark/builds/326761975).)
> Travis CI: test with Node.js 6 and 8 (not 0.10)

- src/remark/dom.js
A deprecation warning has been issue on Chrome about DOM API  method `document.origin`. I changed  to `window.origin`
> Change document.origin to window.origin on DOM JS

- README.md
cicero serves presentation slides written in markdown using remark or
reveal.js, directly from github or gitlab
> mention cicero as tool integrating with remark

- .travis.yml
- make.js
- package.json
- test/runner.html
The PhantomJS and mocha-phantomjs projects have been deprecated and the mocha-chrome is a suggested project to migrate to. I wasn't able to get the mocha-phantomjs to work locally, and the CI was failing due to phantomjs as well. Still need to test that this works on Windows (works fine on MacOS).
> Move from mocha-phantomjs to mocha-chrome for tests

- src/remark/models/slideshow.js
This PR adds a configuration setting that allows you to exclude presenter notes from all slides. For example:
```js
var slideshow = remark.create({
includePresenterNotes: false,
});
```
This feature is useful if you only want to publish the slides, without the notes. By default, notes will be include if the options is not present or explicitly set to true.
> Add an option to exclude presenter notes

- README.md
Updating the list of contributors (thanks @dvberkel for the script!). 
We will lose the links to GitHub repos, however, I think it might be hard to figure out all the GH repos. Perhaps at some point, we could switch to https://allcontributors.org/.
> Update the list of contributors

- src/remark/models/slideshow.js
- test/remark/models/slideshow_test.js
This issue reproed only if the first slide has `count: false` - we have a unit test that was passing when the `count:false` is not on the first slide. However, adding `count: false` to the first slide, fails the test.
Let's assume we have the following slides:
```
count:false
Slide A
---
Slide B
```
When we parse the slides we check if the slide is included (based on the classes) and if it's not a layout slide as well as if it should be counted. The code inside the if statement does not execute, so the slides.byNumber[slideNumber] is undefined
```
if (slideIsIncluded && slide.properties.layout !== 'true' && slide.properties.count !== 'false') {
slideNumber++;
slides.byNumber[slideNumber] = [];
}
```
Later though, we call slides.byNumber[slideNumber].push(slideViewModel); and that's what's …
> Fixing the issue with `count: false` on the first slide
